apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: TierTemplate
metadata:
  name: appstudio-contributor
  namespace: toolchain-host-operator
spec:
  objects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: appstudio-maintainer-user-actions
      namespace: {{ .namespace }}
    rules:
    - apiGroups:
      - appstudio.redhat.com
      resources:
      - applications
      - components
      - componentdetectionqueries
      verbs:
      - get
      - list
      - watch