apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-tiers
  namespace: gitops
spec:
  destination:
    namespace: toolchain-host-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/mfrancisc/tiertemplates.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true